name: Launchable Demo

on:
  pull_request:
  workflow_dispatch:

env:
  SMART_TESTS_TOKEN: "${{ secrets.SMART_TESTS_TOKEN }}"

jobs:
  PreMergeTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "adopt"
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - name: Install Smart Tests CLI
        run: pip install smart-tests-cli
      - name: Compile
        run: mvn compile
      - name: Smart Tests Subset
        run: |
          smart-tests verify
          smart-tests subset maven --from-github-actions --target 20% src/test/java > subset.txt
      - name: Test
        run: mvn test -Dtest=$(cat subset.txt)
      - name: Store Test Results for Smart Tests
        if: always()
        uses: cloudbees-oss/smart-tests-results-upload-action@v1
